import { Inter } from "next/font/google";
import { Providers } from './providers'
import Header from "./components/Header";
import Footer from "./components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SICTRACR",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) =>{
  return (
    <html lang='es'>
      <body>
        <Providers>
          <Header/>
          {children}
          <Footer/>
          </Providers>
      </body>
    </html>
  )
}

export default RootLayout;
